# Generated by Django 4.2.1 on 2023-06-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EkipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(default='', max_length=100)),
                ('soyadi', models.CharField(default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='static/img/user.jpg', upload_to='images/reklamright/%Y/%m/%d', verbose_name='kullanici')),
            ],
        ),
    ]
