# Generated by Django 4.2.1 on 2023-06-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_breakfast_dinner_launch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Müsteriler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(default='', max_length=300)),
                ('aciklama', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('oluşturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='static/img/user.jpg', upload_to='images/user/%Y/%m/%d', verbose_name='users')),
            ],
        ),
    ]
