# Generated by Django 4.2.1 on 2023-06-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_müsteriler'),
    ]

    operations = [
        migrations.AddField(
            model_name='müsteriler',
            name='durum',
            field=models.BooleanField(default=False),
        ),
    ]
