# Generated by Django 4.2.1 on 2023-06-04 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_müsteriler_durum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='müsteriler',
            name='durum',
        ),
    ]
