# Generated by Django 4.2.1 on 2023-06-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_remove_müsteriler_durum'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_adi', models.CharField(default='', max_length=100)),
                ('aciklama', models.CharField(blank=True, default='', max_length=200)),
                ('adres', models.CharField(default='', max_length=120)),
                ('telefon', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=100)),
                ('oluşturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SosyalMedyalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('oluşturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
