# Generated by Django 4.2.1 on 2023-06-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_sitebilgileri_sosyalmedyalar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hakkimizda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('experience', models.IntegerField(blank=True, default=1, null=True)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('start1', models.ImageField(blank=True, default='static/img/menu-1.jpg', upload_to='images/about/%Y/%m/%d', verbose_name='about')),
                ('start2', models.ImageField(blank=True, default='static/img/menu-1.jpg', upload_to='images/about/%Y/%m/%d', verbose_name='about')),
                ('end1', models.ImageField(blank=True, default='static/img/menu-1.jpg', upload_to='images/about/%Y/%m/%d', verbose_name='about')),
            ],
        ),
        migrations.CreateModel(
            name='siteview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('main_image', models.ImageField(blank=True, default='static/img/hero.jpg', upload_to='images/main/%Y/%m/%d', verbose_name='main')),
            ],
        ),
    ]
