# Generated by Django 4.2.1 on 2023-06-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_hakkimizda_siteview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ekipmodel',
            options={'verbose_name': 'Ekip', 'verbose_name_plural': 'Ekipler'},
        ),
        migrations.AddField(
            model_name='ekipmodel',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ekipmodel',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ekipmodel',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ekipmodel',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ekipmodel',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
