# Generated by Django 4.2.1 on 2023-06-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_alter_ekipmodel_options_ekipmodel_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebilgileri',
            name='adres',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sitebilgileri',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitebilgileri',
            name='oluşturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitebilgileri',
            name='telefon',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
