# Generated by Django 4.2.1 on 2023-06-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_alter_sitebilgileri_adres_alter_sitebilgileri_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAyarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbarTitle', models.CharField(blank=True, default='', max_length=120)),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('title_image', models.ImageField(blank=True, default='static/img/menu-2.jpg', upload_to='images/settings/%Y/%m/%d', verbose_name='setting')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('site_title', models.CharField(blank=True, default='', max_length=100)),
                ('siteFooterTitle', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
