# Generated by Django 4.2.1 on 2023-06-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_siteayarlari'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siteİletisim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('adres', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('telefon', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('oluşturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SiteBilgileri',
        ),
        migrations.DeleteModel(
            name='siteview',
        ),
        migrations.DeleteModel(
            name='SosyalMedyalar',
        ),
    ]
