# Generated by Django 4.2.1 on 2023-06-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_alter_breakfast_options_alter_dinner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='WindowTitle',
            field=models.CharField(default='Restorant', help_text='Site pencere başlığı', max_length=39, verbose_name='Site pencere başlığı'),
        ),
    ]
