# Generated by Django 4.2.1 on 2023-06-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_siteayarlari_windowtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='aciklama',
            field=models.CharField(blank=True, default='', max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='aciklama',
            field=models.CharField(blank=True, default='', max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='aciklama',
            field=models.CharField(blank=True, default='', max_length=700, null=True),
        ),
    ]
