# Generated by Django 4.2.1 on 2023-06-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_alter_breakfast_aciklama_alter_dinner_aciklama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='müsteriler',
            name='meslek',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='aciklama',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='fiyat',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='fiyat',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='launch',
            name='fiyat',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
