# Generated by Django 4.2.1 on 2023-06-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0016_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.CharField(default='bi bi-people', help_text='Hizmet başlık icon adı', max_length=300, verbose_name='hizmet başlık iconu'),
        ),
    ]
