# Generated by Django 4.2.1 on 2023-06-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0017_services_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakkimizda',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Hakkımızda iconu'),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.CharField(default='bi bi-people', help_text='Hizmet başlık icon adı https://icons.getbootstrap.com/', max_length=300, verbose_name='hizmet başlık iconu'),
        ),
    ]
