# Generated by Django 4.2.1 on 2023-06-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0018_hakkimizda_icon_alter_services_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakkimizda',
            name='end2',
            field=models.ImageField(blank=True, default='static/img/menu-1.jpg', upload_to='images/about/%Y/%m/%d', verbose_name='Son 2'),
        ),
        migrations.AlterField(
            model_name='hakkimizda',
            name='end1',
            field=models.ImageField(blank=True, default='static/img/menu-1.jpg', upload_to='images/about/%Y/%m/%d', verbose_name='Son 1'),
        ),
        migrations.AlterField(
            model_name='hakkimizda',
            name='start1',
            field=models.ImageField(blank=True, default='static/img/menu-1.jpg', upload_to='images/about/%Y/%m/%d', verbose_name='İlk 1'),
        ),
        migrations.AlterField(
            model_name='hakkimizda',
            name='start2',
            field=models.ImageField(blank=True, default='static/img/menu-1.jpg', upload_to='images/about/%Y/%m/%d', verbose_name='ilk 2'),
        ),
    ]
