# Generated by Django 4.2.1 on 2023-06-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0019_hakkimizda_end2_alter_hakkimizda_end1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakkimizda',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hakkimizda',
            name='title_icon',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
