# Generated by Django 4.2.1 on 2023-06-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0022_siteayarlari_navbaricon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteayarlari',
            name='site_title',
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='footerDescription',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Footer açıklama'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='footerTitle',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Footer Başlık'),
        ),
    ]
