# Generated by Django 4.2.1 on 2023-06-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0023_remove_siteayarlari_site_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteayarlari',
            name='siteFooterTitle',
        ),
    ]
