# Generated by Django 4.2.1 on 2023-06-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0024_remove_siteayarlari_sitefootertitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200, unique=True)),
                ('soyisim', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('kisi_sayisi', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('ekİstek', models.CharField(max_length=500)),
            ],
        ),
    ]
