# Generated by Django 4.2.1 on 2023-06-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0026_remove_reservations_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='rezervationtarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
