# Generated by Django 4.2.1 on 2023-06-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0027_alter_reservations_rezervationtarihi'),
    ]

    operations = [
        migrations.CreateModel(
            name='SayfaModelleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sayfa ismi')),
                ('link', models.URLField()),
            ],
        ),
    ]
