# Generated by Django 4.2.1 on 2023-06-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0028_sayfamodelleri'),
    ]

    operations = [
        migrations.CreateModel(
            name='HizmetGünleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openDate', models.CharField(help_text='Restorantın açılış günü', max_length=210, verbose_name='Açılış günü')),
                ('closeDate', models.CharField(help_text='Restorantın kapanış günü', max_length=210, verbose_name='Kapanış günü')),
                ('timeOpen', models.TimeField(blank=True, help_text='Kapanış saati', verbose_name='Açılış saati')),
                ('timeClose', models.TimeField(blank=True, help_text='Açılış saati', verbose_name='Kapanış saati')),
            ],
            options={
                'verbose_name': 'Hizmet Günleri',
                'verbose_name_plural': 'Hizmet Günleri',
            },
        ),
        migrations.AlterModelOptions(
            name='sayfamodelleri',
            options={'verbose_name': 'Sayfalar', 'verbose_name_plural': 'Sayfalar'},
        ),
    ]
