# Generated by Django 4.2.1 on 2023-06-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0029_hizmetgünleri_alter_sayfamodelleri_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='windowİcon',
            field=models.ImageField(blank=True, default='static/img/site.png', upload_to='images/site/%Y/%m/%d', verbose_name='Site pencere iconu'),
        ),
    ]
