# Generated by Django 4.2.1 on 2023-06-06 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0030_siteayarlari_windowi_con'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteayarlari',
            old_name='windowİcon',
            new_name='windowIcon',
        ),
    ]
