# Generated by Django 4.2.1 on 2023-06-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0031_rename_windowi_con_siteayarlari_windowicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteayarlari',
            name='windowIcon',
        ),
        migrations.AlterField(
            model_name='hakkimizda',
            name='description',
            field=models.CharField(blank=True, default='', max_length=350, null=True),
        ),
    ]
