# Generated by Django 4.2.1 on 2023-06-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0032_remove_siteayarlari_windowicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='windowIcon',
            field=models.ImageField(blank=True, upload_to='images/site/%Y/%m/%d', verbose_name='Site pencere iconu'),
        ),
    ]
