# Generated by Django 4.2.1 on 2023-06-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0033_siteayarlari_windowicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eposta1Title', models.CharField(blank=True, default='', max_length=100)),
                ('eposta1Mail', models.EmailField(max_length=254)),
                ('eposta2Title', models.CharField(blank=True, default='', max_length=100)),
                ('eposta2Mail', models.EmailField(max_length=254)),
                ('eposta3Title', models.CharField(blank=True, default='', max_length=100)),
                ('eposta3Mail', models.EmailField(max_length=254)),
                ('location', models.TextField(help_text='Restorant konum src linki http://embedgooglemaps.com/en/', verbose_name='Konum embed linki ')),
            ],
            options={
                'verbose_name': 'İletişim Ayarları',
                'verbose_name_plural': 'İletişim Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Userİletisim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=50)),
                ('baslik', models.CharField(default='', max_length=122)),
                ('mesaj', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'kullanıcı iletişim',
                'verbose_name_plural': 'Kullanıcı iletişim',
            },
        ),
    ]
