# Generated by Django 4.2.1 on 2023-06-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0035_alter_contactsettings_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsettings',
            name='eposta1Mail',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='eposta2Mail',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='eposta3Mail',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
    ]
