# Generated by Django 4.2.1 on 2023-06-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0036_alter_contactsettings_eposta1mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsettings',
            name='eposta1Mail',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='eposta2Mail',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='eposta3Mail',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='location',
            field=models.URLField(blank=True, default='', help_text='Restorant konumu iframe içinde bulunan src linki http://embedgooglemaps.com/en/', null=True, verbose_name='Konum embed linki '),
        ),
    ]
