# Generated by Django 4.2.1 on 2023-06-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0037_alter_contactsettings_eposta1mail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useri̇letisim',
            name='email',
        ),
        migrations.AddField(
            model_name='useri̇letisim',
            name='soyisim',
            field=models.CharField(default='', max_length=120),
        ),
    ]
